#!/bin/sh -e

##########################################################################
#   Synopsis:
#       devpub-mount [/dev/]partition
#
#   Description:
#       
#       
#   Arguments:
#       
#   Returns:
#
#   Examples:
#
#   Files:
#
#   Environment:
#
#   See also:
#       
#   History:
#   Date        Name        Modification
#   2023-06-15  J Bacon     Begin
##########################################################################

usage()
{
    printf "Usage: $0 [/dev/]partition\n"
    exit 1
}


##########################################################################
#   Function description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2023-06-15  J Bacon     Begin
##########################################################################

media_manager()
{
    : ${MEDIA_MANAGER:=qmediamanager}
    DISPLAY_ID=$(ps -ax -p `pgrep bin/X` | fgrep bin/X | awk '{ print $6 }')
    
    # Debug
    # printf "DISPLAY_ID = $DISPLAY_ID\n" >> $log
    
    # FIXME: Determine owner of :0
    display_users=$(ps aewwj | grep "DISPLAY=${DISPLAY_ID}" | awk '{ print $1 }' | sort -u)
    for user in $display_users; do
	if su -l $user -c "env DISPLAY=$DISPLAY_ID $MEDIA_MANAGER $mount_point"; then
	    break;
	fi
    done
}


try_mount()
{
    partition=$1
    mount_point=/media/${partition#/dev/}
    mkdir -p $mount_point
    
    # FIXME: chown and chgrp don't work on many filesystems
    # Find a way to set ownership and perms
    if [ -n "$GROUP" ]; then
	chgrp $GROUP $mount_point
    fi
    if [ -n "$MODE" ]; then
	chmod $MODE $mount_point
    fi
    
    ##########################################################################
    #   Determining filesystem type if not straightforward.  The fstyp
    #   command is extremely limited.  We simply try supported filesystems.
    ##########################################################################
    
    printf "$partition $mount_point\n" >> $log
    if /usr/pkg/sbin/mount.exfat $partition $mount_point; then
	printf "Mounted exfat.\n" >> $log
	media_manager $mount_point
    elif /sbin/mount_msdos $partition $mount_point; then
	printf "Mounted FAT.\n" >> $log
	media_manager $mount_point
    elif /sbin/mount_cd9660 $partition $mount_point; then
	printf "Mounted cd9660.\n" >> $log
	media_manager $mount_point
    elif /sbin/mount $partition $mount_point; then
	printf "Mounted FFS.\n" >> $log
	media_manager $mount_point
    else
	printf "Could not mount $partition.\n" >> $log
	return 1
    fi
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
partition=$1
if ! echo $partition | grep -q '^/dev/'; then
    partition=/dev/$partition
fi
log=/var/log/devpub-mount/${partition#/dev/*}
mkdir -p $(dirname $log)
rm -f $log

conf_file=/usr/pkg/etc/devpub-mount.conf
if [ -e $conf_file ]; then
    . $conf_file
fi
try_mount $partition
